using System;
using System.Collections.Generic;

namespace MdCardModTool;

public static class Localizer
{
	private static readonly Dictionary<string, string[]> Strings = new(StringComparer.Ordinal)
	{
		["app.title"] = ["MD 卡片 Mod 工具 2.0.3", "MD 卡片 Mod 工具 2.0.3", "MD カード Mod ツール 2.0.3", "MD Card Mod Tool 2.0.3"],
		["app.subtitle"] = ["MASTER DUEL · 卡图、视觉资源、超框与怪兽动画工作台", "MASTER DUEL · 卡圖、視覺資源、超框與怪獸動畫工作台", "MASTER DUEL · カード画像・ビジュアル・オーバーフレーム・演出", "MASTER DUEL · Card art, visual assets, overframe and animation studio"],
		["nav.cards"] = ["卡片资源", "卡片資源", "カード資源", "Card Assets"],
		["nav.visuals"] = ["视觉资源", "視覺資源", "ビジュアル", "Visual Assets"],
		["nav.animation"] = ["怪兽动画", "怪獸動畫", "モンスター演出", "Monster Animation"],
		["nav.overframe"] = ["卡框／超框", "卡框／超框", "フレーム", "Frames / Overframe"],
		["nav.mods"] = ["Mod 管理", "Mod 管理", "Mod 管理", "Mod Manager"],
		["nav.settings"] = ["设置", "設定", "設定", "Settings"],
		["page.cards.title"] = ["卡片资源工作区", "卡片資源工作區", "カード資源ワークスペース", "Card Asset Workspace"],
		["page.cards.description"] = ["按卡号或四语卡名检索；预览、导出、替换与映射修复共用同一资源解析器。", "依卡號或四語卡名搜尋；預覽、匯出、替換與映射修復共用同一資源解析器。", "カード番号または4言語のカード名で検索し、プレビュー・出力・置換・マッピング修復を一元化します。", "Search by card ID or name in four languages; preview, export, replace, and repair use one resolver."],
		["page.visuals.title"] = ["视觉资源与外观", "視覺資源與外觀", "ビジュアル資源と外観", "Visual Assets & Cosmetics"],
		["page.visuals.description"] = ["决斗场地、壁纸／大厅背景、卡背／卡套、卡盒、硬币、头像与头像框均可直接筛选和替换。", "決鬥場地、桌布／大廳背景、卡背／卡套、卡盒、硬幣、頭像與頭像框皆可直接篩選與替換。", "デュエルフィールド、壁紙、プロテクター、デッキケース、コイン、アイコンを直接絞り込み・置換できます。", "Filter and replace duel fields, wallpapers, sleeves, deck cases, coins, icons, and icon frames."],
		["page.animation.title"] = ["怪兽召唤动画", "怪獸召喚動畫", "モンスター召喚演出", "Monster Summon Animation"],
		["page.animation.description"] = ["预览原版 Spine 动画，并替换已有官方演出的 HD／SD 六项资源；不再提供不可靠的新增演出。", "預覽原版 Spine 動畫，並替換既有官方演出的 HD／SD 六項資源；不再提供不可靠的新增演出。", "公式Spine演出をプレビューし、既存の公式HD／SD 6資源を置換します。不確実な新規演出作成は提供しません。", "Preview original Spine animation and replace the six HD/SD assets of an existing official cut-in. Unreliable new cut-in creation is no longer offered."],
		["page.animation.loading"] = ["正在准备怪兽动画工作区…", "正在準備怪獸動畫工作區…", "モンスター演出ワークスペースを準備中…", "Preparing the monster animation workspace…"],
		["page.animation.error"] = ["无法打开怪兽动画工作区", "無法開啟怪獸動畫工作區", "モンスター演出ワークスペースを開けません", "Could not open the monster animation workspace"],
		["page.frames.title"] = ["卡框与超框", "卡框與超框", "カードフレーム／オーバーフレーム", "Frames & Overframe"],
		["page.frames.description"] = ["保留透明像素 RGB 通道，组合卡框、原画与超框素材并实时预览。", "保留透明像素 RGB 通道，組合卡框、原畫與超框素材並即時預覽。", "透明ピクセルのRGBを保持し、カード枠・イラスト・オーバーフレームを合成してプレビューします。", "Preserve RGB in transparent pixels while composing and previewing frames, art, and overframe assets."],
		["page.frames.loading"] = ["正在暂停后台扫描并准备卡框／超框工作区…", "正在暫停背景掃描並準備卡框／超框工作區…", "バックグラウンドスキャンを一時停止し、フレームを準備中…", "Pausing background scans and preparing the frame workspace…"],
		["page.frames.error"] = ["无法打开卡框／超框工作区", "無法開啟卡框／超框工作區", "フレームワークスペースを開けません", "Could not open the frame workspace"],
		["page.mods.title"] = ["Mod 管理", "Mod 管理", "Mod 管理", "Mod Manager"],
		["page.mods.description"] = ["集中查看已修改与新建 Bundle，导入／导出 Mod，并恢复首次备份。", "集中檢視已修改與新建 Bundle，匯入／匯出 Mod，並復原首次備份。", "変更・新規Bundleをまとめて確認し、Modの入出力と初回バックアップへの復元を行います。", "Review modified and created Bundles, import/export Mods, and restore first backups."],
		["page.settings.title"] = ["应用设置", "應用設定", "アプリ設定", "Application Settings"],
		["page.settings.description"] = ["语言、动效偏好与当前配置位置。界面遵循系统 DPI 和减少动画设置。", "語言、動效偏好與目前設定位置。介面遵循系統 DPI 與減少動畫設定。", "言語・モーション設定・構成ファイルの場所。システムDPIとモーション軽減設定に従います。", "Language, motion preferences, and configuration location. The UI follows system DPI and reduced-motion settings."],
		["catalog.badge"] = ["ASTELLAR 四语目录  ·  {0:N0} 张", "ASTELLAR 四語目錄  ·  {0:N0} 張", "ASTELLAR 4言語  ·  {0:N0} 枚", "ASTELLAR CATALOG  ·  {0:N0} CARDS"],
		["visual.all"] = ["全部外观", "全部外觀", "すべて", "All Visuals"],
		["visual.fields"] = ["决斗场地", "決鬥場地", "デュエルフィールド", "Duel Fields"],
		["visual.wallpaper"] = ["壁纸／大厅", "桌布／大廳", "壁紙／ホーム", "Wallpaper / Home"],
		["visual.sleeves"] = ["卡背／卡套", "卡背／卡套", "プロテクター", "Card Backs / Sleeves"],
		["visual.deckcase"] = ["卡盒", "卡盒", "デッキケース", "Deck Cases"],
		["visual.coin"] = ["硬币", "硬幣", "コイン", "Coins"],
		["visual.profile"] = ["头像装饰", "頭像裝飾", "アイコン装飾", "Profile Cosmetics"],
		["top.game"] = ["游戏目录", "遊戲目錄", "ゲーム", "Game"],
		["top.account"] = ["账号", "帳號", "アカウント", "Account"],
		["top.language"] = ["语言", "語言", "言語", "Language"],
		["top.choose"] = ["选择目录", "選擇目錄", "フォルダー選択", "Choose Folder"],
		["top.search"] = ["搜索卡号或四语卡名…", "搜尋卡號或四語卡名…", "カード番号または4言語のカード名を検索…", "Search card ID or name in four languages…"],
		["search.catalog_match"] = ["Astellar 四语卡片目录", "Astellar 四語卡片目錄", "Astellar 4言語カードカタログ", "Astellar multilingual card catalog"],
		["search.no_results"] = ["没有匹配的卡片", "沒有相符的卡片", "一致するカードがありません", "No matching card"],
		["search.no_results_hint"] = ["可尝试输入完整卡号，或使用简中、繁中、日语、英语卡名。", "可嘗試輸入完整卡號，或使用簡中、繁中、日語、英語卡名。", "完全なカード番号、または中国語・日本語・英語のカード名を入力してください。", "Try a full card ID or a Simplified Chinese, Traditional Chinese, Japanese, or English name."],
		["search.locating"] = ["正在定位卡图", "正在定位卡圖", "カード画像を検索中", "Locating card art"],
		["action.rebuild"] = ["重建索引", "重建索引", "索引を再構築", "Rebuild Index"],
		["action.replace"] = ["替换所选", "替換所選", "選択を置換", "Replace Selected"],
		["action.export"] = ["导出 PNG", "匯出 PNG", "PNG 出力", "Export PNG"],
		["action.restore"] = ["还原所选", "還原所選", "選択を復元", "Restore Selected"],
		["action.backup"] = ["打开备份", "開啟備份", "バックアップ", "Open Backup"],
		["action.locate"] = ["定位卡图", "定位卡圖", "カード画像を検索", "Locate Card Art"],
		["action.visuals"] = ["载入视觉资源", "載入視覺資源", "ビジュアルを読込", "Load Visual Assets"],
		["action.inspect"] = ["检查 Bundle", "檢查 Bundle", "Bundle を検査", "Inspect Bundle"],
		["action.overframe.create"] = ["制作超框／卡框", "製作超框／卡框", "オーバーフレーム／枠を作成", "Create Overframe / Frame"],
		["action.frame.edit"] = ["卡框选择／编辑", "卡框選擇／編輯", "カード枠を選択／編集", "Choose / Edit Frame"],
		["action.frame.studio"] = ["制作超框", "製作超框", "オーバーフレームを作成", "Create Overframe"],
		["action.frame.preview"] = ["卡框预览", "卡框預覽", "カード枠をプレビュー", "Preview Frame"],
		["action.animation.preview"] = ["预览怪兽动画", "預覽怪獸動畫", "モンスター演出を再生", "Preview Monster Animation"],
		["action.animation.raw"] = ["原始动画资源", "原始動畫資源", "元の演出資源", "Original Animation Assets"],
		["action.mods.only"] = ["只看我的 Mod", "只看我的 Mod", "自分の Mod のみ", "My Mods Only"],
		["action.mods.all"] = ["显示全部资源", "顯示全部資源", "すべての資源を表示", "Show All Assets"],
		["action.mods.export"] = ["一键导出全部 Mod", "一鍵匯出全部 Mod", "すべての Mod を出力", "Export All Mods"],
		["action.mods.import"] = ["导入 Mod 包", "匯入 Mod 套件", "Mod パッケージを読込", "Import Mod Package"],
		["context.mods.title"] = ["MOD 管理", "MOD 管理", "MOD 管理", "MOD MANAGER"],
		["context.overframe.title"] = ["超框卡", "超框卡", "オーバーフレーム", "OVERFRAME CARDS"],
		["context.overframe.manage"] = ["管理超框登记", "管理超框登記", "登録表を管理", "Manage Mappings"],
		["context.overframe.hint"] = ["在右侧制作、换框与预览；登记表仅管理卡号与高图卡号的对应关系。", "在右側製作、換框與預覽；登記表僅管理卡號與高圖卡號的對應關係。", "右側で作成・枠変更・プレビューを行い、登録表ではカード番号と高画質画像番号の対応だけを管理します。", "Create, change, and preview frames on the right; mappings only link card IDs to high-resolution art IDs."],
		["action.animation"] = ["打开动画工作区", "開啟動畫工作區", "演出ワークスペース", "Open Animation Workspace"],
		["animation.title"] = ["怪兽召唤动画", "怪獸召喚動畫", "モンスター召喚演出", "Monster Summon Animation"],
		["animation.search.placeholder"] = ["卡号或四语卡名", "卡號或四語卡名", "カード番号または4言語のカード名", "Card ID or name in any language"],
		["animation.quality.auto"] = ["自动高清（推荐）", "自動高清（建議）", "自動高画質（推奨）", "Automatic HD (recommended)"],
		["animation.action.locate"] = ["预览动画", "預覽動畫", "アニメーションを再生", "Preview Animation"],
		["animation.action.rebuild"] = ["重建动画映射", "重建動畫映射", "演出索引を再構築", "Rebuild Animation Index"],
		["animation.action.choose"] = ["选择 GIF／视频／图片序列", "選擇 GIF／影片／圖片序列", "GIF・動画・画像連番を選択", "Choose GIF / Video / Image Sequence"],
		["animation.action.play"] = ["播放", "播放", "再生", "Play"],
		["animation.action.pause"] = ["暂停", "暫停", "一時停止", "Pause"],
		["animation.action.apply"] = ["替换官方 HD／SD 动画", "替換官方 HD／SD 動畫", "公式HD／SD演出を置換", "Replace Official HD/SD Animation"],
		["animation.action.restore"] = ["还原该卡动画", "還原此卡動畫", "このカードの演出を復元", "Restore This Card's Animation"],
		["animation.field.card"] = ["卡片", "卡片", "カード", "Card"],
		["animation.field.name"] = ["原版动画名称", "原版動畫名稱", "公式アニメーション名", "Original Animation"],
		["animation.field.fps"] = ["帧率／游戏速度", "影格率／遊戲速度", "FPS／ゲーム速度", "FPS / Game Speed"],
		["animation.field.start"] = ["视频起始秒", "影片起始秒", "動画開始秒", "Video Start (seconds)"],
		["animation.field.frames"] = ["最多读取帧数", "最多讀取影格數", "最大読込フレーム数", "Maximum Frames"],
		["animation.field.quality"] = ["画质／单帧最长边", "畫質／單幀最長邊", "画質／フレーム長辺", "Quality / Frame Long Edge"],
		["animation.field.atlas"] = ["单张图集上限", "單張圖集上限", "アトラス上限", "Atlas Size Limit"],
		["animation.field.scale"] = ["全游戏画面占比（实时）%", "全遊戲畫面占比（即時）%", "ゲーム画面比率（リアルタイム）%", "Game Canvas Scale (live) %"],
		["animation.field.chroma"] = ["绿幕背景透明化", "綠幕背景透明化", "グリーンバック透過", "Green-screen Transparency"],
		["animation.option.chroma"] = ["自动去绿幕", "自動去綠幕", "グリーンバックを自動除去", "Remove green screen automatically"],
		["animation.note"] = ["100% 对应 Master Duel 完整 16:9 游戏画布（4800×2700），比例调整会即时反映在左侧。\n\n“自动高清”会先探测帧数，再选择图集可容纳的最高画质；绿幕选项会保留柔化后的透明边缘。\n\n仅支持预览与替换已有官方召唤演出的怪兽。研究确认：单独创建六个 Bundle 和强制资格判断仍缺少官方时间轴／内部登记，实机会卡顿且不播放，因此已下架。", "100% 對應 Master Duel 完整 16:9 遊戲畫布（4800×2700），比例調整會即時反映於左側。\n\n「自動高清」會先偵測影格數，再選擇圖集可容納的最高畫質；綠幕選項會保留柔化後的透明邊緣。\n\n僅支援預覽與替換既有官方召喚演出的怪獸。研究確認：單獨建立六個 Bundle 並強制資格判定仍缺少官方時間軸／內部登記，實機會停頓且不播放，因此已下架。", "100% は Master Duel の16:9全画面（4800×2700）に相当し、比率変更は左側へ即時反映されます。\n\n「自動高画質」はフレーム数を調べ、アトラスに収まる最高画質を選びます。グリーンバック除去は滑らかな透過境界を保持します。\n\n公式召喚演出が既にあるモンスターのプレビューと置換のみ対応します。6 Bundleの新規作成と判定強制だけでは公式タイムライン／内部登録が不足し、実機で停止後に再生されないため廃止しました。", "100% represents Master Duel's full 16:9 canvas (4800×2700); scale changes update the preview immediately.\n\nAutomatic HD probes the frame count, then chooses the highest quality that fits the atlas. Green-screen removal preserves softened transparent edges.\n\nOnly monsters with an existing official summon cut-in can be previewed and replaced. Research confirmed that six new Bundles plus a forced eligibility check still lack the official timeline/internal registration and stall without playing, so creation was removed."],
		["animation.preview.drop"] = ["拖入 GIF、视频或图片序列开始预览", "拖入 GIF、影片或圖片序列開始預覽", "GIF・動画・画像連番をドロップしてプレビュー", "Drop a GIF, video, or image sequence to preview"],
		["animation.preview.canvas"] = ["全游戏画布 16:9 · {0}%", "全遊戲畫布 16:9 · {0}%", "ゲーム全画面 16:9 · {0}%", "Full game canvas 16:9 · {0}%"],
		["animation.preview.rendering"] = ["正在边渲染边播放：{0}/{1} 帧…", "正在邊渲染邊播放：{0}/{1} 幀…", "レンダリングしながら再生中：{0}/{1} フレーム…", "Rendering while playing: {0}/{1} frames…"],
		["animation.status.locating"] = ["正在按卡号计算 SD / HighEnd_HD 的 6 个资源路径…", "正在依卡號計算 SD / HighEnd_HD 的 6 個資源路徑…", "カード番号から SD / HighEnd_HD の6資源パスを計算中…", "Resolving the six SD / HighEnd_HD resource paths…"],
		["animation.status.located.complete"] = ["{0} · 可替换{1} · 动画名 {2}", "{0} · 可替換{1} · 動畫名稱 {2}", "{0} · 置換可能{1} · アニメーション {2}", "{0} · Replaceable{1} · Animations {2}"],
		["animation.status.located.fallback"] = ["本卡资源未完整下载 · 正在只读播放同名官方演出 P{0}{1} · 动画名 {2}", "本卡資源未完整下載 · 正在唯讀播放同名官方演出 P{0}{1} · 動畫名稱 {2}", "このカードの素材は未完備 · 同名の公式演出 P{0} を読み取り専用で再生中{1} · {2}", "This card's assets are incomplete · playing equivalent official cut-in P{0} read-only{1} · {2}"],
		["animation.status.located.unsupported"] = ["没有官方召唤演出 · 不支持新增动画{0}", "沒有官方召喚演出 · 不支援新增動畫{0}", "公式召喚演出なし · 新規作成は非対応{0}", "No official summon cut-in · creating a new one is unsupported{0}"],
		["animation.status.located.legacy"] = ["检测到旧测试版创建的动画事务 · 仅允许预览和还原删除{0}", "偵測到舊測試版建立的動畫交易 · 僅允許預覽與還原刪除{0}", "旧テスト版の作成トランザクションを検出 · プレビューと復元削除のみ可能{0}", "Legacy test-build creation transaction detected · preview and restore/delete only{0}"],
		["animation.status.located.none"] = ["没有完整召唤演出资源{0}", "沒有完整召喚演出資源{0}", "完全な召喚演出資源がありません{0}", "No complete summon animation assets{0}"],
		["animation.source.unsupported"] = ["这张怪兽没有官方演出；新增动画功能已下架", "此怪獸沒有官方演出；新增動畫功能已下架", "このモンスターに公式演出はありません。新規作成機能は廃止されました", "This monster has no official cut-in; new animation creation has been removed"],
		["animation.source.notapplicable"] = ["这张卡没有可用的怪兽召唤演出", "此卡沒有可用的怪獸召喚演出", "このカードには利用可能なモンスター召喚演出がありません", "This card has no applicable monster summon cut-in"],
		["animation.preview.unsupported"] = ["NO OFFICIAL ANIMATION\n\n当前版本无法可靠新增召唤演出", "NO OFFICIAL ANIMATION\n\n目前版本無法可靠新增召喚演出", "NO OFFICIAL ANIMATION\n\n召喚演出の新規作成には対応していません", "NO OFFICIAL ANIMATION\n\nA new summon cut-in cannot be added reliably"],
		["animation.preview.notapplicable"] = ["NO MONSTER CUT-IN\n\n当前卡不适用怪兽召唤演出", "NO MONSTER CUT-IN\n\n目前卡片不適用怪獸召喚演出", "NO MONSTER CUT-IN\n\nこのカードはモンスター召喚演出の対象外です", "NO MONSTER CUT-IN\n\nThis card does not use a monster summon cut-in"],
		["animation.prompt.card"] = ["请输入卡号，或可匹配的简中／繁中／日语／英语卡名。", "請輸入卡號，或可匹配的簡中／繁中／日語／英語卡名。", "カード番号、または簡体字／繁体字／日本語／英語のカード名を入力してください。", "Enter a card ID or a matching Simplified Chinese, Traditional Chinese, Japanese, or English name."],
		["animation.error.locate"] = ["定位动画失败", "定位動畫失敗", "アニメーション資源の検索に失敗", "Animation Lookup Failed"],
		["animation.confirm.rebuild.title"] = ["重建动画映射", "重建動畫映射", "アニメーション索引を再構築", "Rebuild Animation Index"],
		["animation.confirm.rebuild.message"] = ["正常情况下会按卡号直接计算 SD / HighEnd_HD 的资源路径，不需要扫描。\n\n这个高级修复操作会扫描 LocalData 与 StreamingAssets 的动画候选，可能需要数分钟；只有游戏更新后路径规则变化时才需要。继续？", "一般會依卡號直接計算 SD / HighEnd_HD 的資源路徑，不需掃描。\n\n此進階修復會掃描 LocalData 與 StreamingAssets 的動畫候選，可能需要數分鐘；只有遊戲更新後路徑規則改變時才需要。繼續嗎？", "通常はカード番号から SD / HighEnd_HD の資源パスを直接計算するため、スキャンは不要です。\n\nこの上級修復では LocalData と StreamingAssets の候補を調べるため数分かかる場合があります。更新でパス規則が変わったときだけ使用してください。続行しますか？", "Normally the SD / HighEnd_HD paths are calculated directly from the card ID.\n\nThis advanced repair scans animation candidates in LocalData and StreamingAssets and may take several minutes. It is only needed if a game update changes path rules. Continue?"],
		["animation.status.scanning"] = ["正在扫描动画资源名…", "正在掃描動畫資源名稱…", "アニメーション資源名をスキャン中…", "Scanning animation asset names…"],
		["animation.status.scanprogress"] = ["扫描 {0:N0}/{1:N0} · 已找到 {2:N0} 个动画资源", "掃描 {0:N0}/{1:N0} · 已找到 {2:N0} 個動畫資源", "スキャン {0:N0}/{1:N0} · アニメーション資源 {2:N0} 個", "Scanning {0:N0}/{1:N0} · {2:N0} animation assets found"],
		["animation.error.rebuild"] = ["重建动画映射失败", "重建動畫映射失敗", "アニメーション索引の再構築に失敗", "Animation Index Rebuild Failed"],
		["animation.dialog.media.title"] = ["选择 GIF、视频或多张图片序列", "選擇 GIF、影片或多張圖片序列", "GIF・動画・複数画像の連番を選択", "Choose a GIF, Video, or Image Sequence"],
		["animation.dialog.media.filter"] = ["动画、视频与图片|*.gif;*.mp4;*.webm;*.mov;*.avi;*.mkv;*.m4v;*.apng;*.png;*.jpg;*.jpeg;*.webp;*.bmp;*.tif;*.tiff|所有文件|*.*", "動畫、影片與圖片|*.gif;*.mp4;*.webm;*.mov;*.avi;*.mkv;*.m4v;*.apng;*.png;*.jpg;*.jpeg;*.webp;*.bmp;*.tif;*.tiff|所有檔案|*.*", "アニメーション・動画・画像|*.gif;*.mp4;*.webm;*.mov;*.avi;*.mkv;*.m4v;*.apng;*.png;*.jpg;*.jpeg;*.webp;*.bmp;*.tif;*.tiff|すべてのファイル|*.*", "Animation, Video, and Images|*.gif;*.mp4;*.webm;*.mov;*.avi;*.mkv;*.m4v;*.apng;*.png;*.jpg;*.jpeg;*.webp;*.bmp;*.tif;*.tiff|All Files|*.*"],
		["animation.status.probing"] = ["正在低清探测实际帧数与画面比例…", "正在以低畫質偵測實際幀數與畫面比例…", "低解像度でフレーム数と画面比率を確認中…", "Probing frame count and aspect ratio at low resolution…"],
		["animation.status.extractauto"] = ["检测到 {0:N0} 帧，正在按 {1} px 自动高清抽帧…", "偵測到 {0:N0} 幀，正在以 {1} px 自動高畫質擷取…", "{0:N0} フレームを検出。{1} px の自動高画質で抽出中…", "Detected {0:N0} frames; extracting at automatic HD {1} px…"],
		["animation.status.extractfixed"] = ["正在按 {0} px 用 FFmpeg 抽取画面…", "正在以 {0} px 使用 FFmpeg 擷取畫面…", "FFmpeg で {0} px のフレームを抽出中…", "Extracting frames at {0} px with FFmpeg…"],
		["animation.error.media"] = ["无法读取动画源", "無法讀取動畫來源", "アニメーション素材を読み込めません", "Could Not Read Animation Source"],
		["animation.source.drop"] = ["拖入或选择 GIF / 视频后在左侧预览", "拖入或選擇 GIF / 影片後在左側預覽", "GIF・動画をドロップまたは選択すると左側に表示します", "Drop or choose a GIF / video to preview it on the left"],
		["animation.quality.resolved.auto"] = ["自动高清，上限 {0} px", "自動高畫質，上限 {0} px", "自動高画質、上限 {0} px", "Automatic HD, limit {0} px"],
		["animation.quality.resolved.fixed"] = ["固定上限 {0} px", "固定上限 {0} px", "固定上限 {0} px", "Fixed limit {0} px"],
		["animation.source.media"] = ["{0}\n{1:N0} 帧 · 当前 {2} FPS · {3:0.00} 秒 · {4}×{5}（{6}）{7}", "{0}\n{1:N0} 幀 · 目前 {2} FPS · {3:0.00} 秒 · {4}×{5}（{6}）{7}", "{0}\n{1:N0} フレーム · 現在 {2} FPS · {3:0.00} 秒 · {4}×{5}（{6}）{7}", "{0}\n{1:N0} frames · {2} FPS · {3:0.00} sec · {4}×{5} ({6}){7}"],
		["animation.source.transparent"] = [" · 绿幕已透明", " · 綠幕已透明", " · グリーンバック透過済み", " · green screen removed"],
		["animation.status.preview.loading"] = [" · 正在读取当前动画预览…", " · 正在讀取目前動畫預覽…", " · 現在のアニメーションを読込中…", " · loading current animation preview…"],
		["animation.status.preview.complex"] = [" · 原版骨骼动画", " · 原版骨骼動畫", " · 公式ボーンアニメーション", " · original skeletal animation"],
		["animation.status.preview.playing"] = [" · 正在预览当前动画", " · 正在預覽目前動畫", " · 現在のアニメーションをプレビュー中", " · previewing current animation"],
		["animation.source.complex"] = ["当前为原版多骨骼 / 网格 Spine 动画\n不会把拆散的关节图集冒充预览；导入 GIF / 视频后可实时查看替换效果", "目前為原版多骨骼 / 網格 Spine 動畫\n不會把拆散的關節圖集冒充預覽；匯入 GIF / 影片後可即時查看替換效果", "現在は公式の複数ボーン／メッシュ Spine アニメーションです\n分解されたパーツ画像をプレビューとして偽装せず、GIF・動画を読み込むと置換結果を確認できます", "This is an original multi-bone / mesh Spine animation\nSeparated joint textures are not shown as a fake preview; import a GIF or video to preview the replacement"],
		["animation.preview.complex"] = ["CURRENT SPINE ANIMATION\n\n原版复杂骨骼动画已定位\n拖入 GIF / 视频查看待替换效果", "CURRENT SPINE ANIMATION\n\n已定位原版複雜骨骼動畫\n拖入 GIF / 影片查看待替換效果", "CURRENT SPINE ANIMATION\n\n公式の複雑なボーンアニメーションを検出\nGIF・動画をドロップして置換結果を確認", "CURRENT SPINE ANIMATION\n\nOriginal complex skeletal animation located\nDrop a GIF or video to preview the replacement"],
		["animation.source.current"] = ["当前游戏动画 · {0}\n{1:N0} 帧 · {2} FPS · {3:0.00} 秒 · 全画布 {4}%", "目前遊戲動畫 · {0}\n{1:N0} 幀 · {2} FPS · {3:0.00} 秒 · 全畫布 {4}%", "現在のゲームアニメーション · {0}\n{1:N0} フレーム · {2} FPS · {3:0.00} 秒 · 全画面 {4}%", "Current game animation · {0}\n{1:N0} frames · {2} FPS · {3:0.00} sec · full canvas {4}%"],
		["animation.prompt.apply"] = ["请先定位一张怪兽卡并导入 GIF、视频或图片序列。魔法与陷阱没有怪兽召唤 Cut-in。", "請先定位一張怪獸卡並匯入 GIF、影片或圖片序列。魔法與陷阱沒有怪獸召喚 Cut-in。", "モンスターカードを選び、GIF・動画・画像連番を読み込んでください。魔法・罠にはモンスター召喚 Cut-in がありません。", "Locate a monster card and import a GIF, video, or image sequence first. Spells and traps do not have monster summon cut-ins."],
		["animation.prompt.officialonly"] = ["只支持替换已有官方召唤演出的怪兽。该卡没有可安全替换的官方六项动画资源。", "僅支援替換既有官方召喚演出的怪獸。此卡沒有可安全替換的官方六項動畫資源。", "既存の公式召喚演出があるモンスターのみ置換できます。このカードには安全に置換できる公式6資源がありません。", "Only monsters with an existing official summon cut-in can be replaced. This card has no safe official six-asset set to replace."],
		["animation.prompt.legacyrestore"] = ["这是旧测试版创建的实验动画。为避免继续产生无效 Bundle，只能预览或点击“还原该卡动画”删除。", "這是舊測試版建立的實驗動畫。為避免繼續產生無效 Bundle，只能預覽或按下「還原此卡動畫」刪除。", "旧テスト版が作成した実験演出です。無効なBundleを増やさないため、プレビューまたは「このカードの演出を復元」で削除のみ可能です。", "This experimental animation was created by an older test build. To avoid more invalid Bundles, it can only be previewed or removed with Restore This Card's Animation."],
		["animation.operation.create"] = ["创建", "建立", "作成", "create"],
		["animation.operation.modify"] = ["修改", "修改", "変更", "modify"],
		["animation.confirm.apply.title"] = ["确认写入召唤动画", "確認寫入召喚動畫", "召喚アニメーションの書込み確認", "Confirm Summon Animation Write"],
		["animation.confirm.apply.message"] = ["将为卡号 {0} {1}已有官方演出的 HD/SD Texture2D、Atlas 与 JS。\n\n全部目标均须已存在且形成完整配对；写入前会备份，失败会自动回滚。继续？", "將為卡號 {0} {1}既有官方演出的 HD/SD Texture2D、Atlas 與 JS。\n\n全部目標皆須已存在並形成完整配對；寫入前會備份，失敗會自動復原。繼續嗎？", "カード番号 {0} の既存公式演出（HD/SD Texture2D・Atlas・JS）を{1}します。\n\nすべての対象が既存かつ完全に対応している必要があります。書込み前にバックアップし、失敗時は自動復元します。続行しますか？", "This will {1} the existing official HD/SD Texture2D, Atlas, and JS assets for card {0}.\n\nEvery target must already exist as a complete pair. Files are backed up before writing, and failures roll back automatically. Continue?"],
		["animation.status.building"] = ["正在生成单张 Spine 图集…", "正在產生單張 Spine 圖集…", "単一 Spine アトラスを生成中…", "Building the Spine atlas…"],
		["animation.status.compressing"] = ["图集 {0}×{1} · 正在 BC7 压缩并写入 6 个 Bundle…", "圖集 {0}×{1} · 正在以 BC7 壓縮並寫入 6 個 Bundle…", "アトラス {0}×{1} · BC7 圧縮して6個のBundleへ書込中…", "Atlas {0}×{1} · compressing to BC7 and writing six Bundles…"],
		["animation.status.completed"] = ["替换完成 · {0} 帧 / {1} FPS · 全画布 {2}% · 图集 {3}×{4}", "替換完成 · {0} 幀 / {1} FPS · 全畫布 {2}% · 圖集 {3}×{4}", "置換完了 · {0} フレーム / {1} FPS · 全画面 {2}% · アトラス {3}×{4}", "Completed · {0} frames / {1} FPS · full canvas {2}% · atlas {3}×{4}"],
		["animation.message.completed.title"] = ["动画写入完成", "動畫寫入完成", "アニメーション書込み完了", "Animation Write Complete"],
		["animation.message.completed"] = ["两套召唤动画资源已经全部写入、验证并纳入恢复记录。{0}", "兩套召喚動畫資源已全部寫入、驗證並納入復原記錄。{0}", "両画質の召喚アニメーション資源を書込み、検証して復元記録へ追加しました。{0}", "Both summon animation tiers were written, validated, and added to the restore record.{0}"],
		["animation.message.launch.restart"] = ["\n\n请完全退出并重新启动 Master Duel 后测试。", "\n\n請完全結束並重新啟動 Master Duel 後測試。", "\n\nMaster Duel を完全に終了して再起動後、確認してください。", "\n\nExit Master Duel completely, restart it, and then test."],
		["animation.error.replace"] = ["动画替换失败（已回滚）", "動畫替換失敗（已回復）", "アニメーション置換に失敗（ロールバック済み）", "Animation Replacement Failed (Rolled Back)"],
		["animation.prompt.restore"] = ["请先输入卡号并定位动画资源。", "請先輸入卡號並定位動畫資源。", "カード番号を入力してアニメーション資源を検索してください。", "Enter a card ID and locate its animation assets first."],
		["animation.confirm.restore.title"] = ["还原动画", "還原動畫", "アニメーションを復元", "Restore Animation"],
		["animation.confirm.restore.message"] = ["确认把卡号 {0} 的动画 Bundle 全部还原为首次替换前的版本？", "確定將卡號 {0} 的動畫 Bundle 全部還原為首次替換前的版本？", "カード番号 {0} の全アニメーションBundleを初回置換前へ戻しますか？", "Restore every animation Bundle for card {0} to its state before the first replacement?"],
		["animation.status.restoring"] = ["正在还原动画 Bundle…", "正在還原動畫 Bundle…", "アニメーションBundleを復元中…", "Restoring animation Bundles…"],
		["animation.status.restore.none"] = ["没有找到该卡的动画备份", "找不到此卡的動畫備份", "このカードのアニメーションバックアップがありません", "No animation backup was found for this card"],
		["animation.status.restore.count"] = ["已还原 {0} 个动画 Bundle", "已還原 {0} 個動畫 Bundle", "アニメーションBundleを {0} 個復元しました", "Restored {0} animation Bundles"],
		["animation.message.restore.none"] = ["该卡尚未由本工具替换，或备份目录不存在。", "此卡尚未由本工具替換，或備份目錄不存在。", "このカードはまだ本ツールで置換されていないか、バックアップフォルダーがありません。", "This card has not been replaced by this tool, or its backup folder does not exist."],
		["animation.message.restore.count"] = ["已还原 {0} 个 Bundle。", "已還原 {0} 個 Bundle。", "Bundleを {0} 個復元しました。", "Restored {0} Bundles."],
		["animation.error.restore"] = ["还原失败", "還原失敗", "復元に失敗", "Restore Failed"],
		["animation.error.game.title"] = ["请先退出游戏", "請先結束遊戲", "先にゲームを終了してください", "Exit the Game First"],
		["animation.error.game.running"] = ["Master Duel 仍在运行。请先完全退出游戏，再替换或还原动画 Bundle，避免文件占用或更新丢失。", "Master Duel 仍在執行。請先完全結束遊戲，再替換或還原動畫 Bundle，以免檔案被占用或更新遺失。", "Master Duel が実行中です。ファイル使用中や更新消失を避けるため、完全に終了してからアニメーションBundleを置換・復元してください。", "Master Duel is still running. Exit it completely before replacing or restoring animation Bundles to avoid locked files or lost updates."],
		["raw.title"] = ["原始动画资源 · P{0}", "原始動畫資源 · P{0}", "元のアニメーション資源 · P{0}", "Raw Animation Assets · P{0}"],
		["raw.banner.title"] = ["原始怪兽动画资源", "原始怪獸動畫資源", "モンスター演出の元資源", "RAW MONSTER ANIMATION ASSETS"],
		["raw.banner.subtitle"] = ["P{0} · PNG / ATLAS / JSON · SD + HIGHEND_HD", "P{0} · PNG / ATLAS / JSON · SD + HIGHEND_HD", "P{0} · PNG / ATLAS / JSON · SD + HIGHEND_HD", "P{0} · PNG / ATLAS / JSON · SD + HIGHEND_HD"],
		["raw.warning"] = ["高级功能：Atlas、JSON 与 PNG 必须互相匹配", "進階功能：Atlas、JSON 與 PNG 必須互相匹配", "上級機能：Atlas・JSON・PNG は相互に対応している必要があります", "Advanced: Atlas, JSON, and PNG must match"],
		["raw.section.assets"] = ["关联资源", "關聯資源", "関連資源", "Linked Assets"],
		["raw.section.assets.subtitle"] = ["双击或拖入文件替换所选", "按兩下或拖入檔案以替換所選", "ダブルクリックまたはドロップで選択資源を置換", "Double-click or drop a file to replace the selection"],
		["raw.section.preview"] = ["资源预览", "資源預覽", "資源プレビュー", "Asset Preview"],
		["raw.section.preview.subtitle"] = ["PNG / 文本预览", "PNG / 文字預覽", "PNG / テキストプレビュー", "PNG / TEXT PREVIEW"],
		["raw.action.exportall"] = ["导出全部 6 个文件", "匯出全部 6 個檔案", "6ファイルをすべて出力", "Export All 6 Files"],
		["raw.action.importall"] = ["批量导入编辑目录", "批次匯入編輯目錄", "編集フォルダーを一括読込", "Import Edited Folder"],
		["raw.action.exportselected"] = ["导出所选", "匯出所選", "選択を出力", "Export Selected"],
		["raw.action.replaceselected"] = ["替换所选", "替換所選", "選択を置換", "Replace Selected"],
		["raw.action.restorebundle"] = ["恢复所选 Bundle", "復原所選 Bundle", "選択 Bundle を復元", "Restore Selected Bundle"],
		["raw.action.openfolder"] = ["打开导出目录", "開啟匯出目錄", "出力フォルダーを開く", "Open Export Folder"],
		["raw.note"] = ["导出全部会同时生成 _动画资源映射.json。可在外部编辑同目录文件后使用“批量导入编辑目录”；任何一步失败都会恢复本次写入前的全部 Bundle。", "全部匯出時會同時產生 _動畫資源映射.json。可在外部編輯同目錄檔案後使用「批次匯入編輯目錄」；任何步驟失敗都會還原本次寫入前的全部 Bundle。", "すべて出力すると _动画资源映射.json も作成されます。同じフォルダーのファイルを編集後、「編集フォルダーを一括読込」を使用できます。途中で失敗した場合は今回の書込み前の全 Bundle に戻します。", "Export All also creates _动画资源映射.json. Edit files in that folder, then use Import Edited Folder; if any step fails, every Bundle touched by the operation is rolled back."],
		["raw.column.profile"] = ["版本 / 区域", "版本 / 區域", "バージョン／リージョン", "Version / Region"],
		["raw.column.kind"] = ["文件类型", "檔案類型", "ファイル種類", "File Type"],
		["raw.column.name"] = ["资源名", "資源名稱", "資源名", "Asset Name"],
		["raw.column.pathid"] = ["PathID", "PathID", "PathID", "PathID"],
		["raw.column.bundle"] = ["Bundle 路径", "Bundle 路徑", "Bundle パス", "Bundle Path"],
		["raw.kind.texture"] = ["PNG 图集", "PNG 圖集", "PNG アトラス", "PNG Atlas"],
		["raw.kind.atlas"] = ["Atlas 文本", "Atlas 文字", "Atlas テキスト", "Atlas Text"],
		["raw.kind.skeleton"] = ["Spine JSON", "Spine JSON", "Spine JSON", "Spine JSON"],
		["raw.status.ready"] = ["选择关联资源以预览或导出。", "選擇關聯資源以預覽或匯出。", "関連資源を選択してプレビューまたは出力します。", "Select a linked asset to preview or export."],
		["raw.status.locating"] = ["正在定位 SD / HighEnd_HD 原始动画资源…", "正在定位 SD / HighEnd_HD 原始動畫資源…", "SD / HighEnd_HD の元資源を検索中…", "Locating SD / HighEnd_HD raw animation assets…"],
		["raw.status.located"] = ["{0} · 共 {1} 个关联资源 · {2}", "{0} · 共 {1} 個關聯資源 · {2}", "{0} · 関連資源 {1} 個 · {2}", "{0} · {1} linked assets · {2}"],
		["raw.status.located.fallback"] = ["卡号 P{0} 使用同名官方资源 P{1}（只读） · {2} · 共 {3} 项", "卡號 P{0} 使用同名官方資源 P{1}（唯讀） · {2} · 共 {3} 項", "P{0} は同名の公式資源 P{1} を読み取り専用で使用 · {2} · {3} 項", "P{0} uses equivalent official assets P{1} read-only · {2} · {3} items"],
		["raw.completeness.complete"] = ["完整", "完整", "完全", "Complete"],
		["raw.completeness.incomplete"] = ["资源不完整", "資源不完整", "資源不足", "Incomplete"],
		["raw.status.reading"] = ["正在读取所选底层资源…", "正在讀取所選底層資源…", "選択した元資源を読込中…", "Reading the selected raw asset…"],
		["raw.status.read"] = ["已读取 {0}", "已讀取 {0}", "{0} を読み込みました", "Read {0}"],
		["raw.preview.truncated"] = ["[预览已截断]", "[預覽已截斷]", "[プレビューを省略しました]", "[Preview truncated]"],
		["raw.details"] = ["{0} · {1}\n{2} · PathID {3}\n{4} / {5}", "{0} · {1}\n{2} · PathID {3}\n{4} / {5}", "{0} · {1}\n{2} · PathID {3}\n{4} / {5}", "{0} · {1}\n{2} · PathID {3}\n{4} / {5}"],
		["raw.prompt.selectasset"] = ["请先选择一个动画资源。", "請先選擇一個動畫資源。", "先にアニメーション資源を選択してください。", "Select an animation asset first."],
		["raw.prompt.selectreplace"] = ["请先选择要替换的底层资源。", "請先選擇要替換的底層資源。", "置換する元資源を選択してください。", "Select the raw asset to replace first."],
		["raw.prompt.equivalent.readonly"] = ["卡号 P{0} 当前只读显示同名官方资源 P{1}。为避免把另一资源号误写成该卡，导入、替换和恢复均已禁用。", "卡號 P{0} 目前唯讀顯示同名官方資源 P{1}。為避免把另一資源號誤寫成此卡，匯入、替換與復原皆已停用。", "P{0} は同名の公式資源 P{1} を読み取り専用で表示しています。別の資源番号への誤書込みを防ぐため、読込・置換・復元は無効です。", "P{0} is showing equivalent official assets P{1} read-only. Import, replace, and restore are disabled to avoid writing another resource id as this card."],
		["raw.filter.png"] = ["PNG 图片|*.png", "PNG 圖片|*.png", "PNG 画像|*.png", "PNG Image|*.png"],
		["raw.filter.atlas"] = ["Spine Atlas|*.atlas", "Spine Atlas|*.atlas", "Spine Atlas|*.atlas", "Spine Atlas|*.atlas"],
		["raw.filter.atlasinput"] = ["Spine Atlas|*.atlas;*.txt", "Spine Atlas|*.atlas;*.txt", "Spine Atlas|*.atlas;*.txt", "Spine Atlas|*.atlas;*.txt"],
		["raw.filter.json"] = ["Spine JSON|*.json", "Spine JSON|*.json", "Spine JSON|*.json", "Spine JSON|*.json"],
		["raw.filter.jsoninput"] = ["Spine JSON|*.json;*.txt", "Spine JSON|*.json;*.txt", "Spine JSON|*.json;*.txt", "Spine JSON|*.json;*.txt"],
		["raw.status.exporting.selected"] = ["正在导出所选资源…", "正在匯出所選資源…", "選択資源を出力中…", "Exporting the selected asset…"],
		["raw.status.exported.path"] = ["已导出：{0}", "已匯出：{0}", "出力しました：{0}", "Exported: {0}"],
		["raw.folder.export.description"] = ["选择 6 个原始动画文件的导出目录", "選擇 6 個原始動畫檔案的匯出目錄", "6個の元アニメーションファイルの出力先を選択", "Choose a folder for the six raw animation files"],
		["raw.folder.export.parent"] = ["MD动画资源", "MD動畫資源", "MDアニメーション資源", "MD Animation Assets"],
		["raw.folder.export.name"] = ["P{0}_动画资源", "P{0}_動畫資源", "P{0}_アニメーション資源", "P{0}_animation-assets"],
		["raw.status.exporting.all"] = ["正在导出 PNG、Atlas、JSON 与回导映射…", "正在匯出 PNG、Atlas、JSON 與回匯映射…", "PNG・Atlas・JSON と再読込マップを出力中…", "Exporting PNG, Atlas, JSON, and the import map…"],
		["raw.status.exported.count"] = ["已导出 {0} 个资源：{1}", "已匯出 {0} 個資源：{1}", "{0} 個の資源を出力しました：{1}", "Exported {0} assets: {1}"],
		["raw.dialog.choosefile"] = ["选择替换文件", "選擇替換檔案", "置換ファイルを選択", "Choose Replacement File"],
		["raw.confirm.single.title"] = ["高级单文件替换", "進階單檔替換", "上級：単一ファイル置換", "Advanced Single-File Replacement"],
		["raw.confirm.single.message"] = ["只替换所选的 {0}：\n{1}\n\n不会自动同步另一套画质资源。PNG、Atlas 与 JSON 不匹配会导致动画无法播放。继续？", "只替換所選的 {0}：\n{1}\n\n不會自動同步另一套畫質資源。PNG、Atlas 與 JSON 不匹配會導致動畫無法播放。繼續嗎？", "選択した {0} だけを置換します：\n{1}\n\nもう一方の画質資源は自動同期されません。PNG・Atlas・JSON が一致しないと演出を再生できません。続行しますか？", "Replace only the selected {0}:\n{1}\n\nThe other quality tier will not be synchronized. Mismatched PNG, Atlas, and JSON files prevent playback. Continue?"],
		["raw.status.replacing"] = ["正在备份并替换所选底层资源…", "正在備份並替換所選底層資源…", "選択した元資源をバックアップして置換中…", "Backing up and replacing the selected raw asset…"],
		["raw.status.replaced"] = ["替换完成：{0}", "替換完成：{0}", "置換しました：{0}", "Replaced: {0}"],
		["raw.folder.import.description"] = ["选择包含 _动画资源映射.json 的编辑目录", "選擇包含 _動畫資源映射.json 的編輯目錄", "_动画资源映射.json を含む編集フォルダーを選択", "Choose the edited folder containing _动画资源映射.json"],
		["raw.confirm.import.title"] = ["批量导入原始动画资源", "批次匯入原始動畫資源", "元アニメーション資源を一括読込", "Import Raw Animation Assets"],
		["raw.confirm.import.message"] = ["将按映射批量写入目录中的 PNG、Atlas 与 JSON。\n\n这是一项高级操作；全部资源会先备份，任一步失败会整批回滚。继续？", "將依映射批次寫入目錄中的 PNG、Atlas 與 JSON。\n\n這是進階操作；全部資源會先備份，任何步驟失敗都會整批回復。繼續嗎？", "マップに従い、フォルダー内の PNG・Atlas・JSON を一括で書き込みます。\n\nこれは上級操作です。すべての資源を先にバックアップし、途中で失敗した場合は一括でロールバックします。続行しますか？", "Write the folder's PNG, Atlas, and JSON files in one mapped transaction.\n\nThis is an advanced operation. Every asset is backed up first, and any failure rolls back the whole batch. Continue?"],
		["raw.status.importing"] = ["正在校验并批量写入原始动画资源…", "正在驗證並批次寫入原始動畫資源…", "元アニメーション資源を検証して一括書込中…", "Validating and importing raw animation assets…"],
		["raw.status.imported"] = ["已批量导入 {0} 个资源", "已批次匯入 {0} 個資源", "{0} 個の資源を一括読込しました", "Imported {0} assets"],
		["raw.message.imported.title"] = ["批量导入完成", "批次匯入完成", "一括読込完了", "Import Complete"],
		["raw.message.imported"] = ["已成功导入 {0} 个原始动画资源。\n请完全退出并重新启动 Master Duel 后测试。", "已成功匯入 {0} 個原始動畫資源。\n請完全結束並重新啟動 Master Duel 後測試。", "{0} 個の元アニメーション資源を読み込みました。\nMaster Duel を完全に終了して再起動後、確認してください。", "Successfully imported {0} raw animation assets.\nExit Master Duel completely, restart it, and then test."],
		["raw.confirm.restore.title"] = ["恢复所选 Bundle", "復原所選 Bundle", "選択 Bundle を復元", "Restore Selected Bundle"],
		["raw.confirm.restore.message"] = ["恢复操作以 Bundle 为单位；如果同一 Bundle 里还有其他改动，也会一起回到首次备份状态。继续？", "復原操作以 Bundle 為單位；若同一 Bundle 還有其他變更，也會一併回到首次備份狀態。繼續嗎？", "復元は Bundle 単位です。同じ Bundle 内の別の変更も初回バックアップ時点へ戻ります。続行しますか？", "Restore works at Bundle level. Other changes in the same Bundle also return to the first-backup state. Continue?"],
		["raw.status.restoring"] = ["正在恢复首次备份…", "正在復原首次備份…", "初回バックアップを復元中…", "Restoring the first backup…"],
		["raw.status.restored"] = ["已恢复所选 Bundle", "已復原所選 Bundle", "選択 Bundle を復元しました", "Selected Bundle restored"],
		["raw.status.nobackup"] = ["没有找到该 Bundle 的首次备份", "找不到該 Bundle 的首次備份", "この Bundle の初回バックアップがありません", "No first backup was found for this Bundle"],
		["raw.error.read"] = ["无法读取动画资源", "無法讀取動畫資源", "アニメーション資源を読み込めません", "Could Not Read Animation Assets"],
		["raw.error.preview"] = ["资源预览失败", "資源預覽失敗", "資源のプレビューに失敗", "Asset Preview Failed"],
		["raw.error.export"] = ["导出失败", "匯出失敗", "出力に失敗", "Export Failed"],
		["raw.error.exportall"] = ["整套导出失败", "整套匯出失敗", "一括出力に失敗", "Full Export Failed"],
		["raw.error.replace"] = ["替换失败（已回滚）", "替換失敗（已回復）", "置換に失敗（ロールバック済み）", "Replacement Failed (Rolled Back)"],
		["raw.error.import"] = ["批量导入失败（已回滚）", "批次匯入失敗（已回復）", "一括読込に失敗（ロールバック済み）", "Import Failed (Rolled Back)"],
		["raw.error.restore"] = ["恢复失败", "復原失敗", "復元に失敗", "Restore Failed"],
		["raw.error.game.running"] = ["请先完全退出 Master Duel，再替换或恢复动画资源。", "請先完全結束 Master Duel，再替換或復原動畫資源。", "Master Duel を完全に終了してから、資源を置換または復元してください。", "Exit Master Duel completely before replacing or restoring animation assets."],
		["raw.error.noexport"] = ["还没有导出目录。请先点击“导出全部 6 个文件”。", "尚無匯出目錄。請先按一下「匯出全部 6 個檔案」。", "出力フォルダーがまだありません。先に「6ファイルをすべて出力」を実行してください。", "There is no export folder yet. Use Export All 6 Files first."],
		["section.groups"] = ["资源分类", "資源分類", "資源カテゴリ", "Resource Groups"],
		["section.assets"] = ["图片资源", "圖片資源", "画像資源", "Image Assets"],
		["section.preview"] = ["实时预览", "即時預覽", "ライブプレビュー", "Live Preview"],
		["section.mods"] = ["Mod 管理", "Mod 管理", "Mod 管理", "Mod Manager"],
		["filter.all"] = ["全部", "全部", "すべて", "All"],
		["list.updating"] = ["正在更新列表…", "正在更新清單…", "リストを更新中…", "Updating list…"],
		["list.count"] = ["{0:N0} / {1:N0} 项", "{0:N0} / {1:N0} 項", "{0:N0} / {1:N0} 件", "{0:N0} / {1:N0} items"],
		["list.global_count"] = ["全局 {0:N0} / {1:N0}", "全域 {0:N0} / {1:N0}", "全体 {0:N0} / {1:N0}", "Global {0:N0} / {1:N0}"],
		["language.zhcn"] = ["简体中文", "簡體中文", "簡体字中国語", "Simplified Chinese"],
		["language.zhtw"] = ["繁體中文", "繁體中文", "繁体字中国語", "Traditional Chinese"],
		["language.ja"] = ["日语", "日語", "日本語", "Japanese"],
		["language.en"] = ["英语", "英語", "英語", "English"],
		["status.ready"] = ["已就绪。选择资源即可预览；写入前会创建首次备份。", "已就緒。選擇資源即可預覽；寫入前會建立首次備份。", "準備完了。資源を選択するとプレビューできます。", "Ready. Select an asset to preview; first writes are backed up."],
		["settings.title"] = ["应用设置", "應用設定", "アプリ設定", "Application Settings"],
		["settings.motion"] = ["减少界面动画", "減少介面動畫", "画面の動きを減らす", "Reduce interface motion"],
		["settings.path"] = ["设置保存在：", "設定儲存於：", "設定ファイル：", "Settings are stored at:"],
		["common.cancel"] = ["取消", "取消", "キャンセル", "Cancel"],
		["common.close"] = ["关闭", "關閉", "閉じる", "Close"]
	};

	public static AppLanguage Language { get; private set; } = AppLanguage.SimplifiedChinese;

	public static event EventHandler? LanguageChanged;

	public static void SetLanguage(AppLanguage language)
	{
		if (Language == language)
		{
			return;
		}
		Language = language;
		LanguageChanged?.Invoke(null, EventArgs.Empty);
	}

	public static string T(string id)
	{
		if (!Strings.TryGetValue(id, out string[]? values))
		{
			return id;
		}
		return values[(int)Language];
	}

	public static string F(string id, params object?[] values) => string.Format(T(id), values);
}
